#
# This script was developed for SweetTutos Tutorials
# www.sweettutos.com
#
include $(GNUSTEP_MAKEFILES)/common.make

# make a simple program in Objective-C, call it CalculatorWithParser
TOOL_NAME = CalculatorWithParser

# The implementation Objective-C file which is going to be compiled
CalculatorWithParser_OBJC_FILES = CalculatorWithParser.m

# Header files of your project
#CalculatorWithParser_HEADER_FILES = xxx.h //here goes all header files (.h). For the moment, on n'en a pas.

# Define compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import

# Include rules for creating a command line tool for Objective-C
include $(GNUSTEP_MAKEFILES)/tool.make
